name: Build Jekyll site
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'
          bundler-cache: true
      
      - name: Install dependencies
        run: bundle install
      
      - name: Build site
        run: bundle exec jekyll build
        
      - name: Upload artifact
        uses: actions/upload-artifact@cc9f55d190e3d7341be8cb44e426d16c0dd8116d # v4.3.1
        with:
          name: site
          path: _site 